=== YangShuailing/cSphere/tools/xml/schemas/changelog.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:complexType name="update_item">
        <xs:sequence>
            <xs:element name="item" minOccurs="1" maxOccurs="unbounded">
                <xs:complexType>
                    <xs:simpleContent>
                        <xs:extension base="xs:string">
                            <xs:attribute name="author" type="xs:string" use="required"/>
                            <xs:attribute name="source" type="xs:string" use="required"/>
                        </xs:extension>
                    </xs:simpleContent>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    <xs:element name="changelog">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="history" minOccurs="1" maxOccurs="1">
                    <xs:complexType>
                        <xs:attribute name="type" type="xs:string" use="required"/>
                        <xs:attribute name="name" type="xs:string" use="required"/>
                    </xs:complexType>
                </xs:element>
                <xs:element name="updates" minOccurs="0" maxOccurs="1">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="update" minOccurs="1" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="information" type="xs:string" minOccurs="1" maxOccurs="1"/>
                                        <xs:element name="instructions" type="xs:string" minOccurs="1" maxOccurs="1"/>
                                        <xs:element name="added" type="update_item" minOccurs="0" maxOccurs="unbounded"/>
                                        <xs:element name="reworked" type="update_item" minOccurs="0" maxOccurs="unbounded"/>
                                        <xs:element name="fixed" type="update_item" minOccurs="0" maxOccurs="unbounded"/>
                                        <xs:element name="removed" type="update_item" minOccurs="0" maxOccurs="unbounded"/>
                                    </xs:sequence>
                                    <xs:attribute name="version" type="xs:string" use="required"/>
                                    <xs:attribute name="published" type="xs:string" use="required"/>
                                    <xs:attribute name="compatible" type="xs:string" use="required"/>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== YangShuailing/cSphere/tools/xml/examples/changelog.xml
<?xml version="1.0" encoding="utf-8" ?>
<changelog xmlns:xs="http://www.w3.org/2001/XMLSchema-instance"
    xs:noNamespaceSchemaLocation="http://www.csphere.eu/xml/schemas/changelog.xsd">
    <history type="plugin" name="default" />
    <updates>
        <update version="0.02" published="2007-04-14" compatible="0.01">
            <information>test1</information>
            <instructions>test2</instructions>
            <added>
                <item author="unknown" source="">test3</item>
                <item author="nobody" source="">test4</item>
            </added>
            <reworked>
                <item author="unknown" source="">test5</item>
                <item author="unknown" source="">test6</item>
            </reworked>
            <fixed>
                <item author="unknown" source="">test7</item>
                <item author="unknown" source="">test8</item>
            </fixed>
            <removed>
                <item author="nobody" source="">test9</item>
                <item author="unknown" source="">test0</item>
            </removed>
        </update>
        <update version="0.01" published="2007-04-14" compatible="">
            <information>test1</information>
            <instructions>test2</instructions>
            <added>
                <item author="unknown" source="">test3</item>
                <item author="nobody" source="">test4</item>
            </added>
        </update>
    </updates>
</changelog>

=== YangShuailing/cSphere/tools/changelog/changelog.xml
<?xml version="1.0" encoding="utf-8" ?>
<changelog xmlns:xs="http://www.w3.org/2001/XMLSchema-instance"
    xs:noNamespaceSchemaLocation="http://www.csphere.eu/xml/schemas/changelog.xsd">
    <history type="system" name="csphere" />
    <updates>
        <update version="2013.0-beta8" published="2014-01-14" compatible="">
            <information>Improved quality assurence possibilities</information>
            <instructions>PHP code and language XML files can now easily be checked in many ways</instructions>
            <added>
                <item author="hajo" source="">Added breadcrumb text option to set it manually</item>
                <item author="tom08" source="">Added javascript file to install for database form</item>
                <item author="hajo" source="">Added theme support for overwriting plugin template files</item>
                <item author="hajo" source="">Added Travis CI (travis.yml) again to show build status</item>
            </added>
            <reworked>
                <item author="hajo" source="">Reworked database query logs so that they show bound data</item>
                <item author="hajo" source="">Reworked languages plugin and added duplication and error detection</item>
                <item author="hajo" source="">Reworked readme.md to contain much more information</item>
                <item author="equal" source="">Reworked theme and plugin template files</item>
            </reworked>
            <fixed>
                <item author="ichraffsnicht" source="">Fixed database install javascript file added by tom08</item>
                <item author="hajo" source="">Fixed https detection and https-only login option</item>
            </fixed>
            <removed>
                <item author="hajo" source="">Removed database order by random support from drivers</item>
                <item author="hajo" source="">Removed service loader error logging and rethrow exception instead</item>
                <item author="hajo" source="">Removed vendor prefixes in directory structure</item>
            </removed>
        </update>
    </updates>
</changelog>
