=== YangShuailing/cSphere/tools/xml/schemas/database.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:complexType name="base_column">
        <xs:attribute name="name" type="xs:string" use="required"/>
    </xs:complexType>
    <xs:complexType name="data_column">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="name" type="xs:string" use="required"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
    <xs:complexType name="data_where">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="column" type="xs:string" use="required"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
    <xs:element name="database">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="plugin" type="xs:string" minOccurs="1" maxOccurs="1"/>
                <xs:element name="tables" minOccurs="0" maxOccurs="1">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="table" minOccurs="1" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="columns" minOccurs="1" maxOccurs="1">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="column" minOccurs="1" maxOccurs="unbounded">
                                                        <xs:complexType>
                                                            <xs:attribute name="name" type="xs:string" use="required"/>
                                                            <xs:attribute name="datatype" type="xs:string" use="required"/>
                                                            <xs:attribute name="max" type="xs:integer" use="required"/>
                                                            <xs:attribute name="default" type="xs:string" use="required"/>
                                                        </xs:complexType>
                                                    </xs:element>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="primary" minOccurs="1" maxOccurs="1">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="column" type="base_column" minOccurs="1" maxOccurs="unbounded"/>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="uniques" minOccurs="0" maxOccurs="unbounded">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="unique" minOccurs="1" maxOccurs="unbounded">
                                                        <xs:complexType>
                                                            <xs:sequence>
                                                                <xs:element name="column" type="base_column" minOccurs="1" maxOccurs="unbounded"/>
                                                            </xs:sequence>
                                                            <xs:attribute name="name" type="xs:string" use="required"/>
                                                        </xs:complexType>
                                                    </xs:element>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="indexes" minOccurs="0" maxOccurs="unbounded">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="index" minOccurs="1" maxOccurs="unbounded">
                                                        <xs:complexType>
                                                            <xs:sequence>
                                                                <xs:element name="column" type="base_column" minOccurs="1" maxOccurs="unbounded"/>
                                                            </xs:sequence>
                                                            <xs:attribute name="name" type="xs:string" use="required"/>
                                                        </xs:complexType>
                                                    </xs:element>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="foreigns" minOccurs="0" maxOccurs="unbounded">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="foreign" minOccurs="1" maxOccurs="unbounded">
                                                        <xs:complexType>
                                                            <xs:sequence>
                                                                <xs:element name="column" minOccurs="1" maxOccurs="unbounded">
                                                                    <xs:complexType>
                                                                        <xs:attribute name="name" type="xs:string" use="required"/>
                                                                        <xs:attribute name="target" type="xs:string" use="required"/>
                                                                    </xs:complexType>
                                                                </xs:element>
                                                            </xs:sequence>
                                                            <xs:attribute name="table" type="xs:string" use="required"/>
                                                        </xs:complexType>
                                                    </xs:element>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                    <xs:attribute name="name" type="xs:string" use="required"/>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="data" minOccurs="0" maxOccurs="1">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="insert" minOccurs="0" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="column" type="data_column" minOccurs="1" maxOccurs="unbounded"/>
                                    </xs:sequence>
                                    <xs:attribute name="table" type="xs:string" use="required"/>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="update" minOccurs="0" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="column" type="data_column" minOccurs="1" maxOccurs="unbounded"/>
                                        <xs:element name="where" type="data_where" minOccurs="0" maxOccurs="unbounded"/>
                                    </xs:sequence>
                                    <xs:attribute name="table" type="xs:string" use="required"/>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="delete" minOccurs="0" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="where" type="data_where" minOccurs="1" maxOccurs="unbounded"/>
                                    </xs:sequence>
                                    <xs:attribute name="table" type="xs:string" use="required"/>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== YangShuailing/cSphere/csphere/plugins/sites/database.xml
<?xml version="1.0" encoding="utf-8" ?>
<database xmlns:xs="http://www.w3.org/2001/XMLSchema-instance"
    xs:noNamespaceSchemaLocation="http://www.csphere.eu/xml/schemas/database.xsd">
    <plugin>sites</plugin>
    <tables>
        <table name="sites">
            <columns>
                <column name="site_id" datatype="serial" max="0" default="" />
                <column name="user_id" datatype="integer" default="0"/>
                <column name="site_title" datatype="varchar" max="120" default="" />
                <column name="site_content" datatype="longtext" max="0" default="" />
                <column name="site_layout" datatype="integer" max="0" default="0" />
                <column name="site_publish" datatype="integer" max="2" default="0" />
            </columns>
            <primary>
                <column name="site_id" />
            </primary>
            <uniques>
                <unique name="site_title">
                    <column name="site_title" />
                </unique>
            </uniques>
        </table>
    </tables>
    <data>
        <insert table="options">
            <column name="option_plugin">sites</column>
            <column name="option_name">title_length_list</column>
            <column name="option_value">25</column>
        </insert>
        <insert table="options">
            <column name="option_plugin">sites</column>
            <column name="option_name">title_length_manage</column>
            <column name="option_value">25</column>
        </insert>
    </data>
</database>

=== YangShuailing/cSphere/csphere/plugins/policies/database.xml
<?xml version="1.0" encoding="utf-8" ?>
<database xmlns:xs="http://www.w3.org/2001/XMLSchema-instance"
    xs:noNamespaceSchemaLocation="http://www.csphere.eu/xml/schemas/database.xsd">
    <plugin>policies</plugin>
    <tables>
        <table name="policies">
            <columns>
                <column name="policie_id" datatype="serial" max="0" default="" />
                <column name="policie_content" datatype="longtext" max="0" default="" />
                <column name="policie_date" datatype="integer" max="14" default="" />
            </columns>
            <primary>
                <column name="policie_id" />
            </primary>
        </table>
    </tables>
    <data>
        <insert table="policies">
            <column name="policie_content">...</column>
            <column name="policie_date">1403096960</column>
        </insert>
        <insert table="policies">
            <column name="policie_content">...</column>
            <column name="policie_date">1403096960</column>
        </insert>
        <insert table="policies">
            <column name="policie_content">...</column>
            <column name="policie_date">1403096960</column>
        </insert>
    </data>
</database>

=== YangShuailing/cSphere/csphere/plugins/tags/database.xml
<?xml version="1.0" encoding="utf-8" ?>
<database xmlns:xs="http://www.w3.org/2001/XMLSchema-instance"
    xs:noNamespaceSchemaLocation="http://www.csphere.eu/xml/schemas/database.xsd">
    <plugin>tags</plugin>
    <tables>
        <table name="tags">
            <columns>
                <column name="tag_id" datatype="serial" max="0" default="" />
                <column name="tag_name" datatype="varchar" max="80" default="" />
                <column name="tag_since" datatype="integer" max="0" default="0" />
            </columns>
            <primary>
                <column name="tag_id" />
            </primary>
            <uniques>
                <unique name="tag_name">
                    <column name="tag_name" />
                </unique>
            </uniques>
        </table>
    </tables>
    <data>
    </data>
</database>

=== YangShuailing/cSphere/csphere/plugins/blog/database.xml
<?xml version="1.0" encoding="utf-8" ?>
<database xmlns:xs="http://www.w3.org/2001/XMLSchema-instance"
    xs:noNamespaceSchemaLocation="http://www.csphere.eu/xml/schemas/database.xsd">
    <plugin>blog</plugin>
    <tables>
        <table name="blog">
            <columns>
                <column name="blog_id" datatype="serial" max="0" default="" />
                <column name="user_id" datatype="integer" default="0"/>
                <column name="blog_title" datatype="varchar" max="120" default="" />
                <column name="blog_content" datatype="longtext" default="" />
                <column name="blog_date" datatype="integer" max="14" default="" />
                <column name="blog_publish" datatype="integer" max="2" default="0" />
            </columns>
            <primary>
                <column name="blog_id" />
            </primary>
            <uniques>
                <unique name="blog_title">
                    <column name="blog_title" />
                </unique>
            </uniques>
        </table>
    </tables>
    <data>
        <insert table="options">
            <column name="option_plugin">blog</column>
            <column name="option_name">title_length_list</column>
            <column name="option_value">25</column>
        </insert>
        <insert table="options">
            <column name="option_plugin">blog</column>
            <column name="option_name">title_length_manage</column>
            <column name="option_value">25</column>
        </insert>
    </data>
</database>

=== YangShuailing/cSphere/csphere/plugins/contact/database.xml
<?xml version="1.0" encoding="utf-8" ?>
<database xmlns:xs="http://www.w3.org/2001/XMLSchema-instance"
    xs:noNamespaceSchemaLocation="http://www.csphere.eu/xml/schemas/database.xsd">
    <plugin>contact</plugin>
    <tables>
        <table name="contact">
            <columns>
                <column name="contact_id" datatype="serial" max="0" default="" />
                <column name="contact_name" datatype="varchar" max="80" default="" />
                <column name="contact_date" datatype="integer" max="0" default="0" />
                <column name="contact_mail" datatype="varchar" max="80" default="" />
                <column name="contact_url" datatype="varchar" max="200" default="" />
                <column name="contact_subject" datatype="varchar" max="200" default="" />
                <column name="contact_message" datatype="text" max="0" default="" />
            </columns>
            <primary>
                <column name="contact_id" />
            </primary>
        </table>
    </tables>
</database>

=== YangShuailing/cSphere/csphere/plugins/groups/database.xml
<?xml version="1.0" encoding="utf-8" ?>
<database xmlns:xs="http://www.w3.org/2001/XMLSchema-instance"
    xs:noNamespaceSchemaLocation="http://www.csphere.eu/xml/schemas/database.xsd">
    <plugin>groups</plugin>
    <tables>
        <table name="groups">
            <columns>
                <column name="group_id" datatype="serial" max="0" default="" />
                <column name="group_name" datatype="varchar" max="80" default="" />
                <column name="group_since" datatype="integer" max="0" default="0" />
                <column name="group_url" datatype="varchar" max="200" default="" />
                <column name="group_info" datatype="text" max="0" default="" />
            </columns>
            <primary>
                <column name="group_id" />
            </primary>
            <uniques>
                <unique name="group_name">
                    <column name="group_name" />
                </unique>
            </uniques>
        </table>
    </tables>
    <data>
        <insert table="options">
            <column name="option_plugin">groups</column>
            <column name="option_name">main_id</column>
            <column name="option_value">0</column>
        </insert>
    </data>
</database>

=== YangShuailing/cSphere/tools/xml/examples/database.xml
<?xml version="1.0" encoding="utf-8" ?>
<database xmlns:xs="http://www.w3.org/2001/XMLSchema-instance"
    xs:noNamespaceSchemaLocation="http://www.csphere.eu/xml/schemas/database.xsd">
    <plugin>users</plugin>
    <tables>
        <table name="users">
            <columns>
                <column name="users_id" datatype="serial" max="0" default="" />
                <column name="users_nick" datatype="varchar" max="80" default="" />
                <column name="users_password" datatype="varchar" max="80" default="" />
                <column name="users_email" datatype="varchar" max="80" default="" />
                <column name="users_active" datatype="integer" max="1" default="0" />
                <column name="users_info" datatype="text" max="0" default="" />
            </columns>
            <primary>
                <column name="users_id" />
            </primary>
            <uniques>
                <unique name="users_email">
                    <column name="users_email" />
                </unique>
            </uniques>
            <indexes>
                <index name="users_login">
                    <column name="users_email" />
                    <column name="users_password" />
                </index>
            </indexes>
            <foreigns>
                <foreign table="groups">
                    <column name="users_id" target="users_id" />
                </foreign>
            </foreigns>
        </table>
    </tables>
    <data>
        <insert table="users">
            <column name="users_nick">admin</column>
            <column name="users_active">0</column>
        </insert>
        <update table="users">
            <column name="users_active">1</column>
            <where column="users_nick">admin</where>
        </update>
        <delete table="users">
            <where column="users_id">3</where>
        </delete>
    </data>
</database>

=== YangShuailing/cSphere/csphere/plugins/access/database.xml
<?xml version="1.0" encoding="utf-8" ?>
<database xmlns:xs="http://www.w3.org/2001/XMLSchema-instance"
    xs:noNamespaceSchemaLocation="http://www.csphere.eu/xml/schemas/database.xsd">
    <plugin>access</plugin>
    <tables>
        <table name="access_group">
            <columns>
                <column name="access_group_id" datatype="serial" max="0" default="" />
                <column name="group_id" datatype="integer" default="0"/>
                <column name="access_group_permission" datatype="varchar" max="220" default="" />
                <column name="access_group_value" datatype="varchar" max="10" default="0" />
            </columns>
            <primary>
                <column name="access_group_id" />
            </primary>
        </table>
        <table name="access_user">
            <columns>
                <column name="access_user_id" datatype="serial" max="0" default="" />
                <column name="group_id" datatype="integer" default="0"/>
                <column name="access_user_permission" datatype="varchar" max="220" default="" />
                <column name="access_user_value" datatype="varchar" max="10" default="0" />
            </columns>
            <primary>
                <column name="access_user_id" />
            </primary>
        </table>
    </tables>
</database>
