=== YangShuailing/cSphere/tools/xml/schemas/language.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:complexType name="lang_define">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="name" type="xs:string" use="required"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
    <xs:element name="language">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="translation" minOccurs="1" maxOccurs="1">
                    <xs:complexType>
                        <xs:attribute name="type" type="xs:string" use="required"/>
                        <xs:attribute name="name" type="xs:string" use="required"/>
                        <xs:attribute name="short" type="xs:string" use="required"/>
                        <xs:attribute name="version_min" type="xs:float" use="required"/>
                        <xs:attribute name="version_max" type="xs:float" />
                    </xs:complexType>
                </xs:element>
                <xs:element name="vendor" type="xs:string" minOccurs="1" maxOccurs="1"/>
                <xs:element name="version" type="xs:float" minOccurs="1" maxOccurs="1"/>
                <xs:element name="published" type="xs:date" minOccurs="1" maxOccurs="1"/>
                <xs:element name="copyright" type="xs:string" minOccurs="1" maxOccurs="1"/>
                <xs:element name="license" type="xs:string" minOccurs="1" maxOccurs="1"/>
                <xs:element name="name" type="xs:string" minOccurs="1" maxOccurs="1"/>
                <xs:element name="info" type="xs:string" minOccurs="1" maxOccurs="1"/>
                <xs:element name="engine" minOccurs="1" maxOccurs="1">
                    <xs:complexType>
                        <xs:attribute name="name" type="xs:string" use="required"/>
                        <xs:attribute name="version_min" type="xs:float" use="required"/>
                        <xs:attribute name="version_max" type="xs:float"/>
                    </xs:complexType>
                </xs:element>
                <xs:element name="icon" minOccurs="1" maxOccurs="1">
                    <xs:complexType>
                        <xs:simpleContent>
                            <xs:extension base="xs:string">
                                <xs:attribute name="type" type="xs:string" use="required"/>
                            </xs:extension>
                        </xs:simpleContent>
                    </xs:complexType>
                </xs:element>
                <xs:element name="authors" minOccurs="1" maxOccurs="1">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="current" type="xs:string" minOccurs="1" maxOccurs="unbounded"/>
                            <xs:element name="past" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="contact" minOccurs="1" maxOccurs="1">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="email" minOccurs="1" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:attribute name="adress" type="xs:string" use="required"/>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="web" minOccurs="1" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:attribute name="url" type="xs:anyURI" use="required"/>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="definitions" minOccurs="1" maxOccurs="1">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="define" type="lang_define" minOccurs="1" maxOccurs="unbounded"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== YangShuailing/cSphere/csphere/plugins/contact/languages/de.xml
<?xml version="1.0" encoding="utf-8" ?>
<language xmlns:xs="http://www.w3.org/2001/XMLSchema-instance"
    xs:noNamespaceSchemaLocation="http://www.csphere.eu/xml/schemas/language.xsd">
    <translation type="plugin" name="contact" version_min="0.1" short="de" />
    <vendor>csphere</vendor>
    <version>0.1</version>
    <published>2012-03-01</published>
    <copyright>cSphere Team</copyright>
    <license>Simplified BSD License</license>
    <name>Contact</name>
    <info>Stellt ein Kontaktvormular bereit</info>
    <engine name="csphere" version_min="2013.0" />
    <icon type="famfamfam">de</icon>
    <authors>
        <current>cSphere Team</current>
        <past>cSphere Team</past>
    </authors>
    <contact>
        <email adress="contact@csphere.eu" />
        <web url="http://www.csphere.eu" />
    </contact>
    <definitions>
        <define name="contact">Kontakt</define>
        <define name="subject">Betreff</define>
        <define name="message">Nachricht</define>
        <define name="answer">Antwort</define>
    </definitions>
</language>

=== YangShuailing/cSphere/csphere/plugins/members/languages/en.xml
<?xml version="1.0" encoding="utf-8" ?>
<language xmlns:xs="http://www.w3.org/2001/XMLSchema-instance"
    xs:noNamespaceSchemaLocation="http://www.csphere.eu/xml/schemas/language.xsd">
    <translation type="plugin" name="members" version_min="0.1" short="en" />
    <vendor>csphere</vendor>
    <version>0.1</version>
    <published>2012-03-01</published>
    <copyright>cSphere Team</copyright>
    <license>Simplified BSD License</license>
    <name>Members</name>
    <info>Assign users to groups</info>
    <engine name="csphere" version_min="2013.0" />
    <icon type="famfamfam">gb</icon>
    <authors>
        <current>cSphere Team</current>
        <past>cSphere Team</past>
    </authors>
    <contact>
        <email adress="contact@csphere.eu" />
        <web url="http://www.csphere.eu" />
    </contact>
    <definitions>
        <define name="group_admin">Group admin</define>
        <define name="group_name">Group name</define>
        <define name="group_or_user">Group or user</define>
        <define name="members">Members</define>
        <define name="memberships">Memberships</define>
    </definitions>
</language>

=== YangShuailing/cSphere/csphere/themes/admin/languages/de.xml
<?xml version="1.0" encoding="utf-8" ?>
<language xmlns:xs="http://www.w3.org/2001/XMLSchema-instance"
    xs:noNamespaceSchemaLocation="http://www.csphere.eu/xml/schemas/language.xsd">
    <translation type="template" name="admin" version_min="0.1" short="de" />
    <vendor>csphere</vendor>
    <version>0.1</version>
    <published>2012-03-01</published>
    <copyright>cSphere Team</copyright>
    <license>Simplified BSD License</license>
    <name>Admin</name>
    <info>Dieses Theme ist Bestandteil des Standard-Paketes</info>
    <engine name="csphere" version_min="2013.0" />
    <icon type="famfamfam">de</icon>
    <authors>
        <current>cSphere Team</current>
        <past>cSphere Team</past>
    </authors>
    <contact>
        <email adress="contact@csphere.eu" />
        <web url="http://www.csphere.eu" />
    </contact>
    <definitions>
        <define name="admin">Admin</define>
        <define name="content">Inhalte</define>
        <define name="system">System</define>
    </definitions>
</language>

=== YangShuailing/cSphere/csphere/plugins/policies/languages/en.xml
<?xml version="1.0" encoding="utf-8" ?>
<language xmlns:xs="http://www.w3.org/2001/XMLSchema-instance"
    xs:noNamespaceSchemaLocation="http://www.csphere.eu/xml/schemas/language.xsd">
    <translation type="plugin" name="policies" version_min="0.1" short="en" />
    <vendor>csphere</vendor>
    <version>0.1</version>
    <published>2012-03-01</published>
    <copyright>cSphere Team</copyright>
    <license>Simplified BSD License</license>
    <name>Policies</name>
    <info>Manage your policies entries</info>
    <engine name="csphere" version_min="2013.0" />
    <icon type="famfamfam">gb</icon>
    <authors>
        <current>cSphere Team</current>
        <past>cSphere Team</past>
    </authors>
    <contact>
        <email adress="contact@csphere.eu" />
        <web url="http://www.csphere.eu" />
    </contact>
    <definitions>
        <define name="policies">Policies</define>
        <define name="content">Content</define>
        <define name="imprint">Imprint</define>
        <define name="terms_of_use">Terms of use</define>
        <define name="privacy_protection">Privacy protection</define>
    </definitions>
</language>

=== YangShuailing/cSphere/csphere/plugins/environment/languages/en.xml
<?xml version="1.0" encoding="utf-8" ?>
<language xmlns:xs="http://www.w3.org/2001/XMLSchema-instance"
    xs:noNamespaceSchemaLocation="http://www.csphere.eu/xml/schemas/language.xsd">
    <translation type="plugin" name="environment" version_min="0.1" short="en" />
    <vendor>csphere</vendor>
    <version>0.1</version>
    <published>2012-03-01</published>
    <copyright>cSphere Team</copyright>
    <license>Simplified BSD License</license>
    <name>Environment</name>
    <info>Contains software details and other information</info>
    <engine name="csphere" version_min="2013.0" />
    <icon type="famfamfam">gb</icon>
    <authors>
        <current>cSphere Team</current>
        <past>cSphere Team</past>
    </authors>
    <contact>
        <email adress="contact@csphere.eu" />
        <web url="http://www.csphere.eu" />
    </contact>
    <definitions>
        <define name="allow_url_fopen">Read from URLs</define>
        <define name="allow_url_include">Execute from URLs</define>
        <define name="disk_space">Disk space</define>
        <define name="environment">Environment</define>
        <define name="extensions">Extensions</define>
        <define name="file_uploads">File uploads</define>
        <define name="hostname">Hostname</define>
        <define name="max_input_time">Form data time limit</define>
        <define name="max_execution_time">Execution time limit</define>
        <define name="memory_limit">Memory limit</define>
        <define name="open_basedir">Secured path</define>
        <define name="operating_system">Operating system</define>
        <define name="php">PHP</define>
        <define name="php_details">PHP Details</define>
        <define name="php_handler">PHP handler</define>
        <define name="php_setting">PHP setting</define>
        <define name="php_version">PHP version</define>
        <define name="post_max_size">Form data size limit</define>
        <define name="short_open_tag">Open PHP like XML</define>
        <define name="space">Space</define>
        <define name="space_total">Total space</define>
        <define name="space_used">Used space</define>
        <define name="space_free">Free space</define>
        <define name="upload_max_filesize">Upload limit per file</define>
        <define name="value">Value</define>
        <define name="webserver">Webserver</define>
    </definitions>
</language>

=== YangShuailing/cSphere/csphere/plugins/access/languages/en.xml
<?xml version="1.0" encoding="utf-8" ?>
<language xmlns:xs="http://www.w3.org/2001/XMLSchema-instance"
    xs:noNamespaceSchemaLocation="http://www.csphere.eu/xml/schemas/language.xsd">
    <translation type="plugin" name="access" version_min="0.1" short="en" />
    <vendor>csphere</vendor>
    <version>0.1</version>
    <published>2012-03-01</published>
    <copyright>cSphere Team</copyright>
    <license>Simplified BSD License</license>
    <name>Access</name>
    <info>Grant users access to plugins</info>
    <engine name="csphere" version_min="2013.0" />
    <icon type="famfamfam">gb</icon>
    <authors>
        <current>cSphere Team</current>
        <past>cSphere Team</past>
    </authors>
    <contact>
        <email adress="contact@csphere.eu" />
        <web url="http://www.csphere.eu" />
    </contact>
    <definitions>
        <define name="access">Access</define>
        <define name="reset">Reset</define>
        <define name="details">Details</define>

        <define name="permission_groupread">Can see Group permissions?</define>
        <define name="permission_groupedit">Can edit Group permissions?</define>
        <define name="permission_reset">Can reset plugin permissions?</define>
    </definitions>
</language>

=== YangShuailing/cSphere/csphere/plugins/debug/languages/de.xml
<?xml version="1.0" encoding="utf-8" ?>
<language xmlns:xs="http://www.w3.org/2001/XMLSchema-instance"
    xs:noNamespaceSchemaLocation="http://www.csphere.eu/xml/schemas/language.xsd">
    <translation type="plugin" name="debug" version_min="0.1" short="de" />
    <vendor>csphere</vendor>
    <version>0.1</version>
    <published>2012-03-01</published>
    <copyright>cSphere Team</copyright>
    <license>Simplified BSD License</license>
    <name>Debug</name>
    <info>Enth√§lt Debug-Werkzeuge und Informationen</info>
    <engine name="csphere" version_min="2013.0" />
    <icon type="famfamfam">de</icon>
    <authors>
        <current>cSphere Team</current>
        <past>cSphere Team</past>
    </authors>
    <contact>
        <email adress="contact@csphere.eu" />
        <web url="http://www.csphere.eu" />
    </contact>
    <definitions>
        <define name="backtrace">Ablaufverfolgung</define>
        <define name="call">Aufruf</define>
        <define name="code">Code</define>
        <define name="component">Komponente</define>
        <define name="database">Datenbank</define>
        <define name="debug">Debug</define>
        <define name="errors">Fehler</define>
        <define name="file">Datei</define>
        <define name="includes">Includes</define>
        <define name="line">Zeile</define>
        <define name="logs">Logs</define>
        <define name="memory">Speicher</define>
        <define name="message">Meldung</define>
        <define name="ms">ms</define>
        <define name="parsetime">Ladezeit</define>
        <define name="step">Schritt</define>
    </definitions>
</language>

=== YangShuailing/cSphere/csphere/plugins/blog/languages/en.xml
<?xml version="1.0" encoding="utf-8" ?>
<language xmlns:xs="http://www.w3.org/2001/XMLSchema-instance"
    xs:noNamespaceSchemaLocation="http://www.csphere.eu/xml/schemas/language.xsd">
    <translation type="plugin" name="blog" version_min="0.1" short="en" />
    <vendor>csphere</vendor>
    <version>0.1</version>
    <published>2012-03-01</published>
    <copyright>cSphere Team</copyright>
    <license>Simplified BSD License</license>
    <name>Blog</name>
    <info>Manage your blog entries</info>
    <engine name="csphere" version_min="2013.0" />
    <icon type="famfamfam">gb</icon>
    <authors>
        <current>cSphere Team</current>
        <past>cSphere Team</past>
    </authors>
    <contact>
        <email adress="contact@csphere.eu" />
        <web url="http://www.csphere.eu" />
    </contact>
    <definitions>
        <define name="blog">Blog</define>
        <define name="content">Content</define>
        <define name="default_public">Default public</define>
        <define name="public">Public</define>
        <define name="title">Title</define>
        <define name="title_length_list">Title Length (List)</define>
        <define name="title_or_tags">Title or tags</define>
    </definitions>
</language>
