=== YangShuailing/cSphere/tools/xml/schemas/language.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:complexType name="lang_define">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="name" type="xs:string" use="required"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
    <xs:element name="language">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="translation" minOccurs="1" maxOccurs="1">
                    <xs:complexType>
                        <xs:attribute name="type" type="xs:string" use="required"/>
                        <xs:attribute name="name" type="xs:string" use="required"/>
                        <xs:attribute name="short" type="xs:string" use="required"/>
                        <xs:attribute name="version_min" type="xs:float" use="required"/>
                        <xs:attribute name="version_max" type="xs:float" />
                    </xs:complexType>
                </xs:element>
                <xs:element name="vendor" type="xs:string" minOccurs="1" maxOccurs="1"/>
                <xs:element name="version" type="xs:float" minOccurs="1" maxOccurs="1"/>
                <xs:element name="published" type="xs:date" minOccurs="1" maxOccurs="1"/>
                <xs:element name="copyright" type="xs:string" minOccurs="1" maxOccurs="1"/>
                <xs:element name="license" type="xs:string" minOccurs="1" maxOccurs="1"/>
                <xs:element name="name" type="xs:string" minOccurs="1" maxOccurs="1"/>
                <xs:element name="info" type="xs:string" minOccurs="1" maxOccurs="1"/>
                <xs:element name="engine" minOccurs="1" maxOccurs="1">
                    <xs:complexType>
                        <xs:attribute name="name" type="xs:string" use="required"/>
                        <xs:attribute name="version_min" type="xs:float" use="required"/>
                        <xs:attribute name="version_max" type="xs:float"/>
                    </xs:complexType>
                </xs:element>
                <xs:element name="icon" minOccurs="1" maxOccurs="1">
                    <xs:complexType>
                        <xs:simpleContent>
                            <xs:extension base="xs:string">
                                <xs:attribute name="type" type="xs:string" use="required"/>
                            </xs:extension>
                        </xs:simpleContent>
                    </xs:complexType>
                </xs:element>
                <xs:element name="authors" minOccurs="1" maxOccurs="1">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="current" type="xs:string" minOccurs="1" maxOccurs="unbounded"/>
                            <xs:element name="past" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="contact" minOccurs="1" maxOccurs="1">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="email" minOccurs="1" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:attribute name="adress" type="xs:string" use="required"/>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="web" minOccurs="1" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:attribute name="url" type="xs:anyURI" use="required"/>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="definitions" minOccurs="1" maxOccurs="1">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="define" type="lang_define" minOccurs="1" maxOccurs="unbounded"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== YangShuailing/cSphere/csphere/plugins/debug/languages/en.xml
<?xml version="1.0" encoding="utf-8" ?>
<language xmlns:xs="http://www.w3.org/2001/XMLSchema-instance"
    xs:noNamespaceSchemaLocation="http://www.csphere.eu/xml/schemas/language.xsd">
    <translation type="plugin" name="debug" version_min="0.1" short="en" />
    <vendor>csphere</vendor>
    <version>0.1</version>
    <published>2012-03-01</published>
    <copyright>cSphere Team</copyright>
    <license>Simplified BSD License</license>
    <name>Debug</name>
    <info>Contains debug tools and information</info>
    <engine name="csphere" version_min="2013.0" />
    <icon type="famfamfam">gb</icon>
    <authors>
        <current>cSphere Team</current>
        <past>cSphere Team</past>
    </authors>
    <contact>
        <email adress="contact@csphere.eu" />
        <web url="http://www.csphere.eu" />
    </contact>
    <definitions>
        <define name="backtrace">Backtrace</define>
        <define name="call">Call</define>
        <define name="code">Code</define>
        <define name="component">Component</define>
        <define name="database">Database</define>
        <define name="debug">Debug</define>
        <define name="errors">Errors</define>
        <define name="file">File</define>
        <define name="includes">Includes</define>
        <define name="line">Line</define>
        <define name="logs">Logs</define>
        <define name="memory">Memory</define>
        <define name="message">Message</define>
        <define name="ms">ms</define>
        <define name="parsetime">Parsetime</define>
        <define name="step">Step</define>
    </definitions>
</language>

=== YangShuailing/cSphere/csphere/plugins/default/languages/en.xml
<?xml version="1.0" encoding="utf-8" ?>
<language xmlns:xs="http://www.w3.org/2001/XMLSchema-instance"
    xs:noNamespaceSchemaLocation="http://www.csphere.eu/xml/schemas/language.xsd">
    <translation type="plugin" name="default" version_min="0.1" short="en" />
    <vendor>csphere</vendor>
    <version>0.1</version>
    <published>2012-03-01</published>
    <copyright>cSphere Team</copyright>
    <license>Simplified BSD License</license>
    <name>English</name>
    <info>Provides basic stuff for e.g. language</info>
    <engine name="csphere" version_min="2013.0" />
    <icon type="famfamfam">gb</icon>
    <authors>
        <current>cSphere Team</current>
        <past>cSphere Team</past>
    </authors>
    <contact>
        <email adress="contact@csphere.eu" />
        <web url="http://www.csphere.eu" />
    </contact>
    <definitions>
        <define name="back">Back</define>
        <define name="continue">Continue</define>
        <define name="control">Control</define>
        <define name="count">Count</define>
        <define name="create">Create</define>
        <define name="default">Default</define>
        <define name="details">Details</define>
        <define name="edit">Edit</define>
        <define name="email">Email</define>
        <define name="hits">Hits</define>
        <define name="list">List</define>
        <define name="manage">Manage</define>
        <define name="no">No</define>
        <define name="no_record_found">No record found</define>
        <define name="options">Options</define>
        <define name="options_success">Options saved with success</define>
        <define name="or">or</define>
        <define name="page">Page</define>
        <define name="password">Password</define>
        <define name="plugins">Plugins</define>
        <define name="record_cancel">Record left untouched</define>
        <define name="record_deleted">Record deleted with success</define>
        <define name="record_success">Record saved with success</define>
        <define name="records">Records</define>
        <define name="remove">Remove</define>
        <define name="remove_sure">Really delete ID "$rid$" of this table?</define>
        <define name="save">Save</define>
        <define name="search">Search</define>
        <define name="scriptinfo">Scriptinfo</define>
        <define name="themes">Themes</define>
        <define name="view">View</define>
        <define name="yes">Yes</define>
    </definitions>
</language>

=== YangShuailing/cSphere/csphere/plugins/plugins/languages/en.xml
<?xml version="1.0" encoding="utf-8" ?>
<language xmlns:xs="http://www.w3.org/2001/XMLSchema-instance"
    xs:noNamespaceSchemaLocation="http://www.csphere.eu/xml/schemas/language.xsd">
    <translation type="plugin" name="plugins" version_min="0.1" short="en" />
    <vendor>csphere</vendor>
    <version>0.1</version>
    <published>2012-03-01</published>
    <copyright>cSphere Team</copyright>
    <license>Simplified BSD License</license>
    <name>Plugins</name>
    <info>Manage installed extensions</info>
    <engine name="csphere" version_min="2013.0" />
    <icon type="famfamfam">gb</icon>
    <authors>
        <current>cSphere Team</current>
        <past>cSphere Team</past>
    </authors>
    <contact>
        <email adress="contact@csphere.eu" />
        <web url="http://www.csphere.eu" />
    </contact>
    <definitions>
        <define name="action">Action</define>
        <define name="authors_current">Current authors</define>
        <define name="authors_past">Past authors</define>
        <define name="contact_email">Email</define>
        <define name="contact_web">Website</define>
        <define name="copyright">Copyright</define>
        <define name="details">Details</define>
        <define name="engine">Engine</define>
        <define name="entries">Entries</define>
        <define name="environment_needed">Needed environment</define>
        <define name="environment_extends">Environment it extends</define>
        <define name="icon">Icon</define>
        <define name="info">Info</define>
        <define name="license">License</define>
        <define name="php_required">Required PHP Version</define>
        <define name="php_extensions">Needed PHP Extensions</define>
        <define name="plugin">Plugin</define>
        <define name="plugins">Plugins</define>
        <define name="published">Published</define>
        <define name="until">until</define>
        <define name="vendor">Vendor</define>
        <define name="version">Version</define>
        <define name="options">Options</define>
        <define name="delete">Delete</define>
        <define name="count">Count</define>
        <define name="plugin_market">Plugin Market</define>
        <define name="manuel_install">Manuel install</define>
    </definitions>
</language>

=== YangShuailing/cSphere/csphere/plugins/sites/languages/en.xml
<?xml version="1.0" encoding="utf-8" ?>
<language xmlns:xs="http://www.w3.org/2001/XMLSchema-instance"
          xs:noNamespaceSchemaLocation="http://www.csphere.eu/xml/schemas/language.xsd">
    <translation type="plugin" name="staticpages" version_min="0.1" short="en"/>
    <vendor>csphere</vendor>
    <version>0.1</version>
    <published>2014-01-08</published>
    <copyright>cSphere Team</copyright>
    <license>Simplified BSD License</license>
    <name>Static Pages</name>
    <info>Manage static pages</info>
    <engine name="csphere" version_min="2013.0"/>
    <icon type="famfamfam">gb</icon>
    <authors>
        <current>cSphere Team</current>
        <past>cSphere Team</past>
    </authors>
    <contact>
        <email adress="contact@csphere.eu"/>
        <web url="http://www.csphere.eu"/>
    </contact>
    <definitions>
        <define name="content">Content</define>
        <define name="error403_description">Access to this page denied. If you think this a mistake, please contact the Administrator.</define>
        <define name="error403_title">Forbidden</define>
        <define name="publish">Publish</define>
        <define name="published">Published</define>
        <define name="sites">Sites</define>
        <define name="show_layout">Show layout</define>
        <define name="title">Title</define>
        <define name="title_length_list">Title Length (List)</define>
        <define name="title_length_manage">Title Length (Manage)</define>
        <define name="title_or_tags">Title or tags</define>
    </definitions>
</language>

=== YangShuailing/cSphere/csphere/plugins/cache/languages/en.xml
<?xml version="1.0" encoding="utf-8" ?>
<language xmlns:xs="http://www.w3.org/2001/XMLSchema-instance"
    xs:noNamespaceSchemaLocation="http://www.csphere.eu/xml/schemas/language.xsd">
    <translation type="plugin" name="cache" version_min="0.1" short="en" />
    <vendor>csphere</vendor>
    <version>0.1</version>
    <published>2012-03-01</published>
    <copyright>cSphere Team</copyright>
    <license>Simplified BSD License</license>
    <name>Cache</name>
    <info>Stores prepared data</info>
    <engine name="csphere" version_min="2013.0" />
    <icon type="famfamfam">gb</icon>
    <authors>
        <current>cSphere Team</current>
        <past>cSphere Team</past>
    </authors>
    <contact>
        <email adress="contact@csphere.eu" />
        <web url="http://www.csphere.eu" />
    </contact>
    <definitions>
        <define name="cache">Cache</define>
        <define name="count">Count</define>
        <define name="clear">Clear cache</define>
        <define name="clear_ok">Cache cleared with success</define>
        <define name="control">Control</define>
        <define name="driver">Driver</define>
        <define name="key">Key</define>
        <define name="no_entry">No entry found</define>
        <define name="size">Size</define>
        <define name="time">Time</define>
    </definitions>
</language>

=== YangShuailing/cSphere/csphere/themes/default/languages/en.xml
<?xml version="1.0" encoding="utf-8" ?>
<language xmlns:xs="http://www.w3.org/2001/XMLSchema-instance"
    xs:noNamespaceSchemaLocation="http://www.csphere.eu/xml/schemas/language.xsd">
    <translation type="template" name="default" version_min="0.1" short="en" />
    <vendor>csphere</vendor>
    <version>0.1</version>
    <published>2012-03-01</published>
    <copyright>cSphere Team</copyright>
    <license>Simplified BSD License</license>
    <name>Default</name>
    <info>This template is shipped with the standard package</info>
    <engine name="csphere" version_min="2013.0" />
    <icon type="famfamfam">gb</icon>
    <authors>
        <current>cSphere Team</current>
        <past>cSphere Team</past>
    </authors>
    <contact>
        <email adress="contact@csphere.eu" />
        <web url="http://www.csphere.eu" />
    </contact>
    <definitions>
        <define name="default">Default</define>
        <define name="home">Home</define>
        <define name="imprint">Imprint</define>
        <define name="team">Team</define>
        <define name="admin">Admin</define>
        <define name="content">Content</define>
        <define name="system">System</define>
    </definitions>
</language>

=== YangShuailing/cSphere/csphere/plugins/languages/languages/en.xml
<?xml version="1.0" encoding="utf-8" ?>
<language xmlns:xs="http://www.w3.org/2001/XMLSchema-instance"
    xs:noNamespaceSchemaLocation="http://www.csphere.eu/xml/schemas/language.xsd">
    <translation type="plugin" name="languages" version_min="0.1" short="en" />
    <vendor>csphere</vendor>
    <version>0.1</version>
    <published>2012-03-01</published>
    <copyright>cSphere Team</copyright>
    <license>Simplified BSD License</license>
    <name>Languages</name>
    <info>Translation tools and details</info>
    <engine name="csphere" version_min="2013.0" />
    <icon type="famfamfam">gb</icon>
    <authors>
        <current>cSphere Team</current>
        <past>cSphere Team</past>
    </authors>
    <contact>
        <email adress="contact@csphere.eu" />
        <web url="http://www.csphere.eu" />
    </contact>
    <definitions>
        <define name="duplication">Duplication</define>
        <define name="language">Language</define>
        <define name="languages">Languages</define>
        <define name="short">Short</define>
        <define name="translated">Translation</define>
        <define name="warn_missing">Missing keys</define>
        <define name="warn_noname">Name must be translated</define>
        <define name="warn_difference">Different keys</define>
        <define name="warn_override">Definition of default plugin overriden</define>
    </definitions>
</language>

=== YangShuailing/cSphere/csphere/plugins/policies/languages/de.xml
<?xml version="1.0" encoding="utf-8" ?>
<language xmlns:xs="http://www.w3.org/2001/XMLSchema-instance"
    xs:noNamespaceSchemaLocation="http://www.csphere.eu/xml/schemas/language.xsd">
    <translation type="plugin" name="policies" version_min="0.1" short="de" />
    <vendor>csphere</vendor>
    <version>0.1</version>
    <published>2012-03-01</published>
    <copyright>cSphere Team</copyright>
    <license>Simplified BSD License</license>
    <name>Rechtliches</name>
    <info>Verwalte deine Rechtlichen Eintr√§ge</info>
    <engine name="csphere" version_min="2013.0" />
    <icon type="famfamfam">de</icon>
    <authors>
        <current>cSphere Team</current>
        <past>cSphere Team</past>
    </authors>
    <contact>
        <email adress="contact@csphere.eu" />
        <web url="http://www.csphere.eu" />
    </contact>
    <definitions>
        <define name="policies">Rechtliches</define>
        <define name="content">Inhalt</define>
        <define name="imprint">Impressum</define>	
        <define name="terms_of_use">Nutzungsbedingungen</define>
        <define name="privacy_protection">Datenschutz</define>
    </definitions>
</language>
