=== YangShuailing/cSphere/tools/xml/schemas/language.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:complexType name="lang_define">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="name" type="xs:string" use="required"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
    <xs:element name="language">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="translation" minOccurs="1" maxOccurs="1">
                    <xs:complexType>
                        <xs:attribute name="type" type="xs:string" use="required"/>
                        <xs:attribute name="name" type="xs:string" use="required"/>
                        <xs:attribute name="short" type="xs:string" use="required"/>
                        <xs:attribute name="version_min" type="xs:float" use="required"/>
                        <xs:attribute name="version_max" type="xs:float" />
                    </xs:complexType>
                </xs:element>
                <xs:element name="vendor" type="xs:string" minOccurs="1" maxOccurs="1"/>
                <xs:element name="version" type="xs:float" minOccurs="1" maxOccurs="1"/>
                <xs:element name="published" type="xs:date" minOccurs="1" maxOccurs="1"/>
                <xs:element name="copyright" type="xs:string" minOccurs="1" maxOccurs="1"/>
                <xs:element name="license" type="xs:string" minOccurs="1" maxOccurs="1"/>
                <xs:element name="name" type="xs:string" minOccurs="1" maxOccurs="1"/>
                <xs:element name="info" type="xs:string" minOccurs="1" maxOccurs="1"/>
                <xs:element name="engine" minOccurs="1" maxOccurs="1">
                    <xs:complexType>
                        <xs:attribute name="name" type="xs:string" use="required"/>
                        <xs:attribute name="version_min" type="xs:float" use="required"/>
                        <xs:attribute name="version_max" type="xs:float"/>
                    </xs:complexType>
                </xs:element>
                <xs:element name="icon" minOccurs="1" maxOccurs="1">
                    <xs:complexType>
                        <xs:simpleContent>
                            <xs:extension base="xs:string">
                                <xs:attribute name="type" type="xs:string" use="required"/>
                            </xs:extension>
                        </xs:simpleContent>
                    </xs:complexType>
                </xs:element>
                <xs:element name="authors" minOccurs="1" maxOccurs="1">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="current" type="xs:string" minOccurs="1" maxOccurs="unbounded"/>
                            <xs:element name="past" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="contact" minOccurs="1" maxOccurs="1">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="email" minOccurs="1" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:attribute name="adress" type="xs:string" use="required"/>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="web" minOccurs="1" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:attribute name="url" type="xs:anyURI" use="required"/>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="definitions" minOccurs="1" maxOccurs="1">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="define" type="lang_define" minOccurs="1" maxOccurs="unbounded"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== YangShuailing/cSphere/csphere/plugins/install/languages/de.xml
<?xml version="1.0" encoding="utf-8" ?>
<language xmlns:xs="http://www.w3.org/2001/XMLSchema-instance"
    xs:noNamespaceSchemaLocation="http://www.csphere.eu/xml/schemas/language.xsd">
    <translation type="plugin" name="install" version_min="0.1" short="de" />
    <vendor>csphere</vendor>
    <version>0.1</version>
    <published>2012-03-01</published>
    <copyright>cSphere Team</copyright>
    <license>Simplified BSD License</license>
    <name>Installation</name>
    <info>Bietet eine Führung durch die Installation</info>
    <engine name="csphere" version_min="2013.0" />
    <icon type="famfamfam">de</icon>
    <authors>
        <current>cSphere Team</current>
        <past>cSphere Team</past>
    </authors>
    <contact>
        <email adress="contact@csphere.eu" />
        <web url="http://www.csphere.eu" />
    </contact>
    <definitions>
        <define name="admin_ok">Administrator erfolgreich gespeichert</define>
        <define name="ajax_full">Erweitertes AJAX</define>
        <define name="ajax_info">Der Hauptinhalt wird damit unabhängig vom Rest der Seite erneuert</define>
        <define name="cache_info">None ist nur für Entwickler gedacht. File nur verwenden, wenn sonst nichts verfügbar ist.</define>
        <define name="cache_ok">Die Datenspeicher-Einstellungen sind korrekt</define>
        <define name="cache_type">Zwischenspeicher</define>
        <define name="conf">Konfiguration</define>
        <define name="config_ok">Konfiguration erfolgreich erstellt</define>
        <define name="db">Datenbank</define>
        <define name="database_ok">Die Datenbank-Einstellungen sind korrekt</define>
        <define name="db_file">Dateiname</define>
        <define name="db_file_info">Pflicht bei SQLite, optional bei LocalDB, ohne Pfadangabe</define>
        <define name="db_prefix">Prefix</define>
        <define name="db_prefix_info">Steht Datenbanktabellennamen voran, nur Buchstaben</define>
        <define name="db_schema">Schema</define>
        <define name="db_schema_info">Name der Datenbank auf dem angegebenen Server</define>
        <define name="debug_mode">Debug Modus</define>
        <define name="debug_info">Aktiviert zusätzliche Anzeigen für Entwickler</define>
        <define name="error_logs">Fehlerlogs anlegen</define>
        <define name="host_info">Valide IP oder DNS, z.B. localhost oder 127.0.0.1</define>
        <define name="install">Installation</define>
        <define name="lang">Sprache</define>
        <define name="language_ok">Die folgende Seite ist wie gewünscht übersetzt</define>
        <define name="logs_info">Speichere auftretende Fehler zur späteren Ansicht</define>
        <define name="mail">E-Mail</define>
        <define name="mail_newline">Zeilenumbruch</define>
        <define name="mail_newline_info">Default verwenden, solange der Dienst keine Abweichung benötigt</define>
        <define name="mail_ok">E-Mail-Einstellungen erfolgreich gespeichert</define>
        <define name="mail_subject">Titel</define>
        <define name="mail_subject_info">Dieser Text steht allen Titeln voran</define>
        <define name="mail_test_fail">Mit den gegebenen Einstellungen ist kein Versand möglich</define>
        <define name="mail_test_subject">Testmail</define>
        <define name="mail_test_text">Das Betrachten dieser Nachricht bedeutet, dass der E-Mailversand klappt.</define>
        <define name="memory">Datenspeicher</define>
        <define name="no_cache">Die Cache-Einstellungen sind fehlerhaft</define>
        <define name="no_cfg">Das Verzeichnis /csphere/config muss beschreibbar sein</define>
        <define name="no_db">Fehler in der Datenbankkonfiguration</define>
        <define name="no_php_ext">Required PHP extensions not loaded</define>
        <define name="port_info">Port, auf dem der Service läuft</define>
        <define name="pretty_urls">Hübsche URLs</define>
        <define name="rewrite_info">Achtung: Benötigt Webserver-spezifische Regeln, siehe Dokumentation</define>
        <define name="server">Servertyp</define>
        <define name="test">Test</define>
        <define name="timeout">Timeout</define>
        <define name="timeout_info">Timeout in Sekunden</define>
        <define name="too_short">Benutzername und Passwort müssen mindestens vier Zeichen lang sein</define>
        <define name="webmaster">Seitenverwalter</define>
        <define name="welcome">Willkommen</define>
        <define name="welcome_info">Dies installiert das cSphere CMS, zum Fortfahren unten klicken</define>
        <define name="zlib_compression">ZLIB Komprimierung</define>
        <define name="zlib_info">Komprimiert HTTP-Antworten mit gzip, empfohlen</define>
    </definitions>
</language>

=== YangShuailing/cSphere/tools/xml/examples/language.xml
<?xml version="1.0" encoding="utf-8" ?>
<language xmlns:xs="http://www.w3.org/2001/XMLSchema-instance"
    xs:noNamespaceSchemaLocation="http://www.csphere.eu/xml/schemas/language.xsd">
    <translation type="plugin" name="news" version_min="0.1"
        short="de" />
    <vendor>acme</vendor>
    <version>0.1</version>
    <published>2007-04-17</published>
    <copyright>cSphere Team</copyright>
    <license>Simplified BSD License</license>
    <name>News</name>
    <info>Nachrichten anzeigen und verwalten</info>
    <engine name="csphere" version_min="2012.0" />
    <icon type="default">layout</icon>
    <authors>
        <current>cSphere Team</current>
        <past>cSphere Team</past>
    </authors>
    <contact>
        <email adress="contact@csphere.eu" />
        <web url="http://www.csphere.eu" />
    </contact>
    <definitions>
        <define name="category">Kategorie</define>
        <define name="no_news_found">Keine Nachricht vorhanden</define>
    </definitions>
</language>

=== YangShuailing/cSphere/csphere/plugins/themes/languages/en.xml
<?xml version="1.0" encoding="utf-8" ?>
<language xmlns:xs="http://www.w3.org/2001/XMLSchema-instance"
    xs:noNamespaceSchemaLocation="http://www.csphere.eu/xml/schemas/language.xsd">
    <translation type="plugin" name="plugins" version_min="0.1" short="en" />
    <vendor>csphere</vendor>
    <version>0.1</version>
    <published>2012-03-01</published>
    <copyright>cSphere Team</copyright>
    <license>Simplified BSD License</license>
    <name>Plugins</name>
    <info>Manage installed extensions</info>
    <engine name="csphere" version_min="2013.0" />
    <icon type="famfamfam">gb</icon>
    <authors>
        <current>cSphere Team</current>
        <past>cSphere Team</past>
    </authors>
    <contact>
        <email adress="contact@csphere.eu" />
        <web url="http://www.csphere.eu" />
    </contact>
    <definitions>
        <define name="action">Action</define>
        <define name="admin">Administration</define>
        <define name="authors_current">Current authors</define>
        <define name="authors_past">Past authors</define>
        <define name="contact_email">Email</define>
        <define name="contact_web">Website</define>
        <define name="contains_designs">Contains designs for</define>
        <define name="copyright">Copyright</define>
        <define name="details">Details</define>
        <define name="engine">Engine</define>
        <define name="entries">Entries</define>
        <define name="environment_needed">Needed environment</define>
        <define name="environment_extends">Environment it extends</define>
        <define name="icon">Icon</define>
        <define name="info">Info</define>
        <define name="install">Installation</define>
        <define name="layout">Layout</define>
        <define name="license">License</define>
        <define name="media">Media</define>
        <define name="mobile">Mobile</define>
        <define name="theme">Theme</define>
        <define name="themes">Themes</define>
        <define name="thumb">Thumb</define>
        <define name="preview">Preview</define>
        <define name="plugin">Plugin</define>
        <define name="published">Published</define>
        <define name="until">until</define>
        <define name="vendor">Vendor</define>
        <define name="version">Version</define>
    </definitions>
</language>

=== YangShuailing/cSphere/csphere/plugins/plugins/languages/de.xml
<?xml version="1.0" encoding="utf-8" ?>
<language xmlns:xs="http://www.w3.org/2001/XMLSchema-instance"
    xs:noNamespaceSchemaLocation="http://www.csphere.eu/xml/schemas/language.xsd">
    <translation type="plugin" name="plugins" version_min="0.1" short="de" />
    <vendor>csphere</vendor>
    <version>0.1</version>
    <published>2012-03-01</published>
    <copyright>cSphere Team</copyright>
    <license>Simplified BSD License</license>
    <name>Plugins</name>
    <info>Verwaltet installierte Erweiterungen</info>
    <engine name="csphere" version_min="2013.0" />
    <icon type="famfamfam">de</icon>
    <authors>
        <current>cSphere Team</current>
        <past>cSphere Team</past>
    </authors>
    <contact>
        <email adress="contact@csphere.eu" />
        <web url="http://www.csphere.eu" />
    </contact>
    <definitions>
        <define name="delete">Entfernen</define>
        <define name="manual_install">Manuell Installieren</define>
        <define name="php_extensions">Ben√∂tigte PHP Erweiterungen</define>
        <define name="plugin_market">Plugin Markt</define>
        <define name="plugins">Plugins</define>
    </definitions>
</language>

=== YangShuailing/cSphere/csphere/plugins/languages/languages/de.xml
<?xml version="1.0" encoding="utf-8" ?>
<language xmlns:xs="http://www.w3.org/2001/XMLSchema-instance"
    xs:noNamespaceSchemaLocation="http://www.csphere.eu/xml/schemas/language.xsd">
    <translation type="plugin" name="languages" version_min="0.1" short="de" />
    <vendor>csphere</vendor>
    <version>0.1</version>
    <published>2012-03-01</published>
    <copyright>cSphere Team</copyright>
    <license>Simplified BSD License</license>
    <name>Languages</name>
    <info>Translation tools and details</info>
    <engine name="csphere" version_min="2013.0" />
    <icon type="famfamfam">de</icon>
    <authors>
        <current>cSphere Team</current>
        <past>cSphere Team</past>
    </authors>
    <contact>
        <email adress="contact@csphere.eu" />
        <web url="http://www.csphere.eu" />
    </contact>
    <definitions>
        <define name="action">Aktion</define>
        <define name="admin">Administration</define>
        <define name="authors_current">Derzeitige Autoren</define>
        <define name="authors_past">Vorherige Autoren</define>
        <define name="contact_email">E-Mail</define>
        <define name="contact_web">Webseite</define>
        <define name="contains_designs">Beinhaltet das Aussehen für</define>
        <define name="copyright">Copyright</define>
        <define name="details">Details</define>
        <define name="engine">Engine</define>
        <define name="icon">Icon</define>
        <define name="info">Info</define>
        <define name="install">Installation</define>
        <define name="language">Sprache</define>
        <define name="languages">Sprachen</define>
        <define name="layout">Layout</define>
        <define name="license">Lizenz</define>
        <define name="short">Kurz</define>
        <define name="plugin">Plugin</define>
        <define name="plugins">Plugins</define>
        <define name="published">Veröffentlich am</define>
        <define name="theme">Theme</define>
        <define name="themes">Themes</define>
        <define name="translated">Übersetzung</define>
        <define name="until">bis</define>
        <define name="vendor">Hersteller</define>
        <define name="version">Version</define>
        <define name="warn_noname">Der Name muss übersetzt sein</define>
        <define name="warn_difference">Unterschied zu anderer Hauptsprache</define>
        <define name="warn_override">Definition des Plugins default überschrieben</define>
    </definitions>
</language>

=== YangShuailing/cSphere/csphere/themes/default/languages/de.xml
<?xml version="1.0" encoding="utf-8" ?>
<language xmlns:xs="http://www.w3.org/2001/XMLSchema-instance"
    xs:noNamespaceSchemaLocation="http://www.csphere.eu/xml/schemas/language.xsd">
    <translation type="template" name="default" version_min="0.1" short="de" />
    <vendor>csphere</vendor>
    <version>0.1</version>
    <published>2012-03-01</published>
    <copyright>cSphere Team</copyright>
    <license>Simplified BSD License</license>
    <name>Standard</name>
    <info>Dieses Theme ist Bestandteil des Standard-Paketes</info>
    <engine name="csphere" version_min="2013.0" />
    <icon type="famfamfam">de</icon>
    <authors>
        <current>cSphere Team</current>
        <past>cSphere Team</past>
    </authors>
    <contact>
        <email adress="contact@csphere.eu" />
        <web url="http://www.csphere.eu" />
    </contact>
    <definitions>
        <define name="default">Standard</define>
        <define name="home">Startseite</define>
        <define name="imprint">Impressum</define>
        <define name="team">Team</define>
        <define name="admin">Administration</define>
        <define name="content">Inhalte</define>
        <define name="system">System</define>
    </definitions>
</language>

=== YangShuailing/cSphere/csphere/plugins/sites/languages/de.xml
<?xml version="1.0" encoding="utf-8" ?>
<language xmlns:xs="http://www.w3.org/2001/XMLSchema-instance"
          xs:noNamespaceSchemaLocation="http://www.csphere.eu/xml/schemas/language.xsd">
    <translation type="plugin" name="staticpages" version_min="0.1" short="de"/>
    <vendor>csphere</vendor>
    <version>0.1</version>
    <published>2014-01-08</published>
    <copyright>cSphere Team</copyright>
    <license>Simplified BSD License</license>
    <name>Statische Seiten</name>
    <info>Verwalte und betrachte statische Seiten</info>
    <engine name="csphere" version_min="2013.0"/>
    <icon type="famfamfam">de</icon>
    <authors>
        <current>cSphere Team</current>
        <past>cSphere Team</past>
    </authors>
    <contact>
        <email adress="contact@csphere.eu"/>
        <web url="http://www.csphere.eu"/>
    </contact>
    <definitions>
        <define name="content">Inhalt</define>
        <define name="error403_description">Der Zugriff zu dieser Seite wurde verweigert. Sollten Sie dies für einen Fehler halten, wenden Sie sich bitte an den Administrator.</define>
        <define name="error403_title">Zugriff verweigert</define>
        <define name="publish">Veröffentlichen</define>
        <define name="published">Veröffentlicht</define>
        <define name="sites">Seiten</define>
        <define name="show_layout">Seitenlayout anzeigen</define>
        <define name="title">Titel</define>
        <define name="title_length_list">Titellänge (Liste)</define>
        <define name="title_length_manage">Titellänge (Verwaltung)</define>
        <define name="title_or_tags">Titel oder Schlagwörter</define>
    </definitions>
</language>

=== YangShuailing/cSphere/csphere/plugins/database/languages/en.xml
<?xml version="1.0" encoding="utf-8" ?>
<language xmlns:xs="http://www.w3.org/2001/XMLSchema-instance"
    xs:noNamespaceSchemaLocation="http://www.csphere.eu/xml/schemas/language.xsd">
    <translation type="plugin" name="database" version_min="0.1" short="en" />
    <vendor>csphere</vendor>
    <version>0.1</version>
    <published>2012-03-01</published>
    <copyright>cSphere Team</copyright>
    <license>Simplified BSD License</license>
    <name>Database</name>
    <info>Overview and tools for database content</info>
    <engine name="csphere" version_min="2013.0" />
    <icon type="famfamfam">gb</icon>
    <authors>
        <current>cSphere Team</current>
        <past>cSphere Team</past>
    </authors>
    <contact>
        <email adress="contact@csphere.eu" />
        <web url="http://www.csphere.eu" />
    </contact>
    <definitions>
        <define name="columns">Columns</define>
        <define name="data">Data</define>
        <define name="database">Database</define>
        <define name="deletes">Deletes</define>
        <define name="encoding">Encoding</define>
        <define name="foreigns">Foreigns</define>
        <define name="indexes">Indexes</define>
        <define name="inserts">Inserts</define>
        <define name="install_it">Installieren</define>
        <define name="install_ok">Tables and data created with success</define>
        <define name="no_data">No data found</define>
        <define name="no_table_found">No table found</define>
        <define name="primary">Primary</define>
        <define name="reload">Reload</define>
        <define name="schema">Schema</define>
        <define name="table">Table</define>
        <define name="table_name_error">Table name is not valid</define>
        <define name="tables">Tables</define>
        <define name="uninstall_it">Deinstallieren</define>
        <define name="uninstall_ok">Tables and options removed with success</define>
        <define name="uniques">Uniques</define>
        <define name="updates">Updates</define>
        <define name="version_client">Client version</define>
        <define name="version_driver">Driver version</define>
        <define name="version_server">Server version</define>
        <define name="where">Where</define>
    </definitions>
</language>
